title = "Le Human"
# generate_feed = true
description = "I do what I do."

# The URL the site will be built for
base_url = "https://lehuman.github.io/website/"
compile_sass = true
minify_html = true
build_search_index = true

[markdown]
highlight_code = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = []
